### ISSUE TITLE
Logo proposal for media server UI

### ISSUE THREAD

**Issue by candyskull920** [ic3y808/Alloy#3]
Hi @ic3y808 
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project for free, I can provide you with a logo for your project

Good day
Skull C.

**Comment by ic3y808** [comment]
Hey @candyskull920 
Sure that would be great, I do want to mention I plan on changing the "media center UI" to something more attractive in the future once this becomes more of what it is targeted to be. Please omit that name from your creative process if possible, that is mostly a placeholder at this point. 

If you use the name/features toward creating icons I would suggest using the targeted future features or just be creative and come up with what you feel! 

Thanks for the offer and posting the issue!

**Comment by candyskull920** [comment]
Hi @ic3y808 
I would like you to give me some information, what exactly is your project and if you want the logo to transmit something specific or want to see some specific colors in the logo

**Comment by ic3y808** [comment]
Hey @candyskull920 

There is nothing specific really to relay other than this is a culmination of media sources. I have renamed the project to "Alloy" (an amalgamation of various media service API's which currently is just subsonic support). Please feel free to express yourself, as you noted you would like to collaborate so I would like to not define what you do. As this is an open source project we can always "upgrade" from the past to something newer when it is relevant if you feel the media you created is not sufficient. 

I am appreciative of any support the project gets, this is currently just a pet project as I cannot find a media center that handles all of what I want and is 100% opensource. It is not currently at the point i want it, but I will be working towards that goal as I noted I cannot find anything that does exaclly what I require.
